# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android -r features/step_definitions --exclude features/ios --tags ~@manual --tags ~@nok --tags ~@negocio --tags ~@novo --tags ~@ios --tags ~@iOS --tags ~@integrado
ios: PLATFORM=ios -r features/support -r features/ios -r features/step_definitions --exclude features/android --tags ~@manual --tags ~@nok --tags ~@negocio --tags ~@novo --tags ~@android --tags ~@integrado



